apiVersion: v1
kind: Service
metadata:
  name: {{ include "premyom-rstudio.fullname" . }}-rstudio
  labels:
    {{- include "premyom-rstudio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rstudio
  ports:
    - name: http
      port: 8080
      targetPort: 8080
