apiVersion: v2
name: premyom-vscode-python
description: Premyom VSCode environment for Onyxia (wrapper autour du chart officiel vscode-python avec une image custom)
type: application
version: 0.1.5
appVersion: "latest"
## 0.1.4: ajout d'un ingress au niveau du wrapper (tentative).
## 0.1.5: ajout d'un `values.schema.json` (x-onyxia) pour que Onyxia injecte `vscode-python.ingress.*` (hostname, ingressClassName, etc.).

dependencies:
  - name: vscode-python
    version: 2.4.2
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
