apiVersion: v2
name: premyom-vscode-python
description: Premyom VSCode environment for Onyxia (wrapper autour du chart officiel vscode-python avec une image custom)
type: application
version: 0.1.4
appVersion: "latest"
## 0.1.4: ajoute l'ingress au niveau du wrapper pour consommer les valeurs Onyxia (ingress.*) quand `vscode-python` est une dépendance.

dependencies:
  - name: vscode-python
    version: 2.4.2
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
