apiVersion: v2
name: premyom-sofa
description: "POC SOFA Simulation Premyom pour Onyxia (desktop web CPU-only), avec SSO et montages S3 (s3fs) basés sur les groupes Keycloak."
type: application
version: 0.1.0
appVersion: "latest"
